services:
  scheduler:
    image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG1
    build:
      context: .
      dockerfile: ./Dockerfile.a
    container_name: docker1
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    ports:
      - "8000:8000"
    restart: always
    
  worker:
    image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG2
    build:
      context: server2
      dockerfile: ./Dockerfile.b
    container_name: docker2
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    ports:
      - "8001:8001"
    restart: always
