services:
  scheduler:
    image: ${ECR_REGISTRY}/${ECR_SCHEDULER_REPOSITORY}:latest
    build:
      context: .
      dockerfile: ./Dockerfile.a
    container_name: docker1
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    ports:
      - "8000:8000"
    restart: always
    
  worker:
    image: ${ECR_REGISTRY}/${ECR_WORKER_REPOSITORY}:latest
    build:
      context: server2
      dockerfile: ./Dockerfile.b
    container_name: docker2
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    ports:
      - "8001:8001"
    restart: always
