services:
  scheduler:
    image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG1
    build:
      context: .
      dockerfile: ./Dockerfile.a
    container_name: scheduler
    restart: always
    
  worker:
    image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG2
    build:
      context: .
      dockerfile: ./Dockerfile.b
    container_name: worker
    ports:
      - 8000:80
    restart: always
